/**
 * Flat re-exports of the OpenAPI component schemas.
 *
 * `types.ts` is regenerated by openapi-typescript on every build and uses
 * the tool's nested `components["schemas"]` shape. This module exposes the
 * same types under their schema names so application code can use them
 * directly without reaching into the nested structure.
 */
import type { components } from "./types.js";

type Schemas = components["schemas"];

export type StatusCode = Schemas["StatusCode"];
export type Staleness = Schemas["Staleness"];
export type StageKind = Schemas["StageKind"];
export type LifecyclePhase = Schemas["LifecyclePhase"];
export type AppName = Schemas["AppName"];
export type Timestamp = Schemas["Timestamp"];
export type Link = Schemas["Link"];
export type AppList = Schemas["AppList"];
export type AppSummary = Schemas["AppSummary"];
export type AppSource = Schemas["AppSource"];
export type OverallStatus = Schemas["OverallStatus"];
export type AppStatus = Schemas["AppStatus"];
export type Stage = Schemas["Stage"];
export type StageEnvelope = Schemas["StageEnvelope"];
export type StageUpdateEvent = Schemas["StageUpdateEvent"];
export type SnapshotEvent = Schemas["SnapshotEvent"];
export type OverallUpdateEvent = Schemas["OverallUpdateEvent"];
export type PingEvent = Schemas["PingEvent"];
export type ErrorEvent = Schemas["ErrorEvent"];

/** Convenience alias for the payload clients pass to stage-update handlers. */
export type StageUpdate = StageUpdateEvent;
