/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Applications visible to the aggregator
         * @description Returns every ArgoCD Application the aggregator's ServiceAccount is permitted
         *     to read, plus each Application's current overall status. Intended for the
         *     `<app-switcher>` combobox.
         *
         *     Supports filtering by source repository to implement the `?repo=` fallback:
         *     when exactly one Application matches, the caller redirects the browser to
         *     `?app=<name>`.
         */
        get: operations["listApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a full status snapshot for one Application
         * @description Returns all 14 lifecycle stages with their current status, summary text,
         *     typed details, deep links to upstream tools, and per-field fetched-at /
         *     staleness metadata.
         */
        get: operations["getAppStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to an Application's live status stream (SSE)
         * @description Opens a long-lived `text/event-stream` connection. On connect the server
         *     sends an `event: snapshot` carrying a full `AppStatus`. Thereafter the
         *     server emits `event: stage-update` whenever a stage's status changes, and
         *     `event: ping` every 20 seconds for keep-alive.
         *
         *     Clients should set the `Accept: text/event-stream` header and use the
         *     standard `EventSource` API or equivalent. The `Last-Event-ID` header is
         *     honoured on reconnect to trigger a fresh snapshot.
         *
         *     OpenAPI does not model SSE natively; the payloads each event carries are
         *     specified by the schemas linked below and by the `x-sse-events` extension.
         */
        get: operations["streamAppEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{name}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force cache bypass on the next read for one Application
         * @description Marks all per-source cache entries for this Application as expired, forcing
         *     the next `GET /status` or next cache read inside an active SSE connection
         *     to hit upstream sources. Rate-limited to 1 request per 30 seconds per
         *     Application to protect upstream rate limits.
         */
        post: operations["refreshApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness/readiness probe
         * @description Returns `200` when the aggregator is serving normally. Returns `503` when
         *     at least one upstream source has been failing continuously for more than
         *     five minutes (per PRD-002 FR7.3).
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Exposes Prometheus-formatted metrics. Not intended for browser use; scraped
         *     by the Prometheus stack via `ServiceMonitor` in `deploy/service-monitor.yaml`.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description DNS-label-safe ArgoCD Application name. Must match the regex used by
         *     Kubernetes for resource names.
         * @example fvh-tfds
         */
        AppName: string;
        /**
         * @description Per-stage health code.
         *
         *     * `ok` — stage is healthy by its own rule.
         *     * `warn` — stage is degraded but not broken (e.g., stale release).
         *     * `fail` — stage is broken (e.g., ArgoCD Degraded, Run 0/N).
         *     * `unknown` — data could not be fetched or interpreted; rendered grey.
         *     * `n/a` — stage does not apply to this Application right now (e.g., Deprecate
         *       with no sunset date).
         * @enum {string}
         */
        StatusCode: "ok" | "warn" | "fail" | "unknown" | "n/a";
        /**
         * @description Freshness label attached to every stage payload.
         *
         *     * `fresh` — value produced by a direct upstream read within the TTL.
         *     * `cached` — value served from cache; still within TTL.
         *     * `stale` — value is past TTL but no fresher data is available yet (the
         *       aggregator is mid-refresh). Clients may display but should flag.
         *     * `fetch-failed` — last fetch attempt failed; value is the last known good
         *       one (if any). Clients MUST render a grey (`unknown`) dot in this case.
         * @enum {string}
         */
        Staleness: "fresh" | "cached" | "stale" | "fetch-failed";
        /**
         * @description Stable string identifier for each of the 14 lifecycle stages. Used as the
         *     OpenAPI discriminator for the `Stage` union so generated TypeScript clients
         *     produce a true discriminated union.
         * @enum {string}
         */
        StageKind: "inception" | "provision" | "develop" | "commit-push" | "ai-review" | "ci-gates" | "release" | "deploy" | "run" | "operate" | "monitor" | "evolve" | "deprecate" | "decommission";
        /** @enum {string} */
        LifecyclePhase: "setup" | "build" | "ship" | "run" | "evolve" | "sunset";
        /**
         * Format: date-time
         * @description RFC 3339 UTC timestamp.
         * @example 2026-04-16T09:30:17Z
         */
        Timestamp: string;
        Link: {
            /** @example ArgoCD */
            label: string;
            /**
             * Format: uri
             * @example https://argocd.fvh.internal/applications/fvh-tfds
             */
            href: string;
        };
        Problem: {
            /**
             * Format: uri
             * @description URI identifying the problem type.
             * @default about:blank
             */
            type: string;
            /**
             * @description Short, human-readable summary.
             * @example Application not found
             */
            title: string;
            /** @example 404 */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
            /** @description OpenTelemetry trace id, if tracing is enabled. */
            trace_id?: string;
        };
        AppList: {
            apps: components["schemas"]["AppSummary"][];
            fetchedAt: components["schemas"]["Timestamp"];
        };
        AppSummary: {
            name: components["schemas"]["AppName"];
            /**
             * @description `deployed` — Application exists in ArgoCD; full 14-stage view is available.
             *     `pre-deploy` — lookup resolved via GitHub repo only; only Build-phase
             *     stages will be populated in the corresponding status snapshot.
             * @enum {string}
             */
            mode: "deployed" | "pre-deploy";
            source: components["schemas"]["AppSource"];
            overall: components["schemas"]["OverallStatus"];
        };
        /** @description Handles derived from the Application record or the fallback repo lookup. */
        AppSource: {
            /** @example ForumViriumHelsinki/tfds */
            repo: string;
            /** @example main */
            defaultBranch?: string;
            /**
             * @description Kubernetes namespace the Application deploys into. Absent in pre-deploy mode.
             * @example tfds
             */
            namespace?: string;
            /**
             * @description AppProject the Application belongs to. Absent in pre-deploy mode.
             * @example platform-automation
             */
            argocdProject?: string;
            /**
             * @description Sentry project slug, inferred from repo name or an `fvh.io/sentry-project` label on the Application.
             * @example tfds
             */
            sentryProject?: string | null;
            /**
             * @description GHCR image repo derived from `deploy/values.yaml`.
             * @example ghcr.io/forumviriumhelsinki/tfds
             */
            imageRepository?: string | null;
        };
        OverallStatus: {
            status: components["schemas"]["StatusCode"];
            /** @example Running · Healthy */
            summary: string;
            /** @description The stage whose status pinned the overall badge, if any. */
            worstStageKind?: components["schemas"]["StageKind"] | null;
        };
        /**
         * @description Full snapshot for one Application. All 14 stages are present; stages whose
         *     data source is not applicable for the current mode return `status: n/a` or
         *     `status: unknown`.
         */
        AppStatus: {
            app: components["schemas"]["AppName"];
            /** @enum {string} */
            mode: "deployed" | "pre-deploy";
            source: components["schemas"]["AppSource"];
            overall: components["schemas"]["OverallStatus"];
            stages: components["schemas"]["Stage"][];
            fetchedAt: components["schemas"]["Timestamp"];
            /** @description Upper bound for how stale any value in this snapshot can be. */
            cacheTtlSeconds?: number;
        };
        /** @description Fields common to every stage. Concrete stages extend this shape. */
        StageEnvelope: {
            /** @description Stage number (1..14), stable. */
            id: number;
            kind: components["schemas"]["StageKind"];
            phase: components["schemas"]["LifecyclePhase"];
            /** @description Human-readable stage title as shown in the UI. */
            title: string;
            status: components["schemas"]["StatusCode"];
            /**
             * @description One-line current-state sentence rendered at the top of the tooltip.
             * @example Synced · Healthy · rev abc123f
             */
            summary?: string;
            links?: components["schemas"]["Link"][];
            fetchedAt: components["schemas"]["Timestamp"];
            staleness: components["schemas"]["Staleness"];
            /**
             * @description Populated when `staleness == fetch-failed`; short reason string.
             * @example github: 502 Bad Gateway
             */
            failureReason?: string;
        };
        Stage: components["schemas"]["InceptionStage"] | components["schemas"]["ProvisionStage"] | components["schemas"]["DevelopStage"] | components["schemas"]["CommitPushStage"] | components["schemas"]["AiReviewStage"] | components["schemas"]["CiGatesStage"] | components["schemas"]["ReleaseStage"] | components["schemas"]["DeployStage"] | components["schemas"]["RunStage"] | components["schemas"]["OperateStage"] | components["schemas"]["MonitorStage"] | components["schemas"]["EvolveStage"] | components["schemas"]["DeprecateStage"] | components["schemas"]["DecommissionStage"];
        InceptionStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "inception";
            details: {
                openIssueCount?: number;
                oldestOpenedAt?: components["schemas"]["Timestamp"] | null;
                latestUpdatedAt?: components["schemas"]["Timestamp"] | null;
                /** @description The `project:*` labels found on the repo. */
                projectLabels?: string[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "inception";
        };
        ProvisionStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "provision";
            details: {
                applicationExists?: boolean;
                applicationCreatedAt?: components["schemas"]["Timestamp"] | null;
                conditions?: {
                    type: string;
                    /** @enum {string} */
                    status: "True" | "False" | "Unknown";
                    message?: string;
                    lastTransitionAt?: components["schemas"]["Timestamp"] | null;
                }[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "provision";
        };
        DevelopStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "develop";
            details: {
                lastCommitAt?: components["schemas"]["Timestamp"] | null;
                lastCommitSha?: string | null;
                lastCommitAuthor?: string | null;
                lastCommitMessage?: string | null;
                commitsLast7d?: number;
                commitsLast30d?: number;
                openPullRequests?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "develop";
        };
        CommitPushStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "commit-push";
            details: {
                sampleSize?: number;
                conventionalCount?: number;
                conventionalRatio?: number;
                lastNonConventional?: {
                    sha?: string;
                    title?: string;
                    /** Format: uri */
                    url?: string;
                } | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "commit-push";
        };
        AiReviewStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "ai-review";
            details: {
                latestPr?: {
                    number: number;
                    /** Format: uri */
                    url: string;
                    title: string;
                    author?: string;
                    openedAt?: components["schemas"]["Timestamp"];
                } | null;
                /** @enum {string} */
                claudeVerdict?: "approved" | "changes-requested" | "commented" | "no-review";
                claudeReviewedAt?: components["schemas"]["Timestamp"] | null;
                /**
                 * @description Most recent non-bot review outcome.
                 * @enum {string}
                 */
                humanVerdict?: "approved" | "changes-requested" | "commented" | "no-review";
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ai-review";
        };
        CiGatesStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "ci-gates";
            details: {
                defaultBranchSha?: string;
                totalChecks?: number;
                successfulChecks?: number;
                failedChecks?: number;
                pendingChecks?: number;
                requiredFailing?: components["schemas"]["CheckSummary"][];
                allChecks?: components["schemas"]["CheckSummary"][];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ci-gates";
        };
        CheckSummary: {
            name: string;
            /** @enum {string} */
            status?: "queued" | "in_progress" | "completed";
            /**
             * @description Populated when `status == completed`; null otherwise.
             * @enum {string|null}
             */
            conclusion?: "success" | "failure" | "neutral" | "cancelled" | "skipped" | "timed_out" | "action_required" | "stale" | null;
            required?: boolean;
            /** Format: uri */
            url?: string;
            completedAt?: components["schemas"]["Timestamp"] | null;
        };
        ReleaseStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "release";
            details: {
                /** @example v1.4.2 */
                latestReleaseTag?: string | null;
                latestReleaseAt?: components["schemas"]["Timestamp"] | null;
                /** Format: uri */
                latestReleaseUrl?: string | null;
                releasePleasePr?: {
                    number: number;
                    /** Format: uri */
                    url: string;
                    openedAt: components["schemas"]["Timestamp"];
                    title?: string;
                } | null;
                /** @description Most recent image tag published to GHCR matching the semver pattern. */
                ghcrImageTag?: string | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "release";
        };
        DeployStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "deploy";
            details: {
                /** @enum {string} */
                syncStatus?: "Synced" | "OutOfSync" | "Unknown";
                /** @enum {string} */
                healthStatus?: "Healthy" | "Progressing" | "Degraded" | "Suspended" | "Missing" | "Unknown";
                /** @description Git SHA currently synced. */
                syncRevision?: string | null;
                syncedAt?: components["schemas"]["Timestamp"] | null;
                /**
                 * @description Latest ArgoCD operation phase; `null` when no operation is active.
                 * @enum {string|null}
                 */
                operationPhase?: "Running" | "Succeeded" | "Failed" | "Error" | "Terminating" | null;
                deployedImageTag?: string | null;
                imageUpdaterLastWriteAt?: components["schemas"]["Timestamp"] | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "deploy";
        };
        RunStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "run";
            details: {
                readyReplicas?: number;
                desiredReplicas?: number;
                availableReplicas?: number;
                updatedReplicas?: number;
                deployments?: {
                    name: string;
                    ready: number;
                    desired: number;
                    available?: number;
                    updated?: number;
                }[];
                recentPodEvents?: {
                    /** @enum {string} */
                    type: "Normal" | "Warning";
                    reason: string;
                    message: string;
                    count?: number;
                    lastSeenAt: components["schemas"]["Timestamp"];
                }[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "run";
        };
        OperateStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "operate";
            details: {
                runbookFound?: boolean;
                /**
                 * @description Path within the repo to the discovered runbook.
                 * @example docs/RUNBOOK.md
                 */
                runbookPath?: string | null;
                /** Format: uri */
                runbookUrl?: string | null;
                alertingFound?: boolean;
                alertingPath?: string | null;
                backupPolicyFound?: boolean;
                backupPolicyPath?: string | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "operate";
        };
        MonitorStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "monitor";
            details: {
                sentryProject?: string | null;
                unresolvedIssueCount?: number;
                newIssues24h?: number;
                eventRate24h?: number;
                eventRateBaseline7d?: number;
                /** @description eventRate24h / eventRateBaseline7d; ≥ 2.0 flips status to `fail`. */
                eventRateRatio?: number | null;
                highSeverityIssues?: {
                    id: string;
                    title: string;
                    /** Format: uri */
                    url: string;
                    /** @enum {string} */
                    level?: "fatal" | "error" | "warning" | "info" | "debug";
                    eventCount: number;
                    lastSeenAt: components["schemas"]["Timestamp"];
                }[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "monitor";
        };
        EvolveStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "evolve";
            details: {
                migrationIssues?: number;
                breakingChangeIssues?: number;
                /** @description Count of `docs/adrs/*.md` with status `Proposed`, if discoverable. */
                openAdrProposals?: number;
                items?: {
                    number: number;
                    title: string;
                    /** Format: uri */
                    url: string;
                    /** @enum {string} */
                    label: "migration" | "breaking-change";
                }[];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "evolve";
        };
        DeprecateStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "deprecate";
            details: {
                /**
                 * Format: date
                 * @description Declared sunset date (annotation `fvh.io/deprecated-on` or repo topic).
                 */
                deprecationDate?: string | null;
                /** @description Negative values indicate the date has passed. */
                daysUntilSunset?: number | null;
                /** @description True if an in-app banner or `DEPRECATED.md` is present in the repo. */
                deprecationNoticeFound?: boolean;
                /** Format: uri */
                noticeUrl?: string | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "deprecate";
        };
        DecommissionStage: components["schemas"]["StageEnvelope"] & {
            /** @constant */
            kind?: "decommission";
            details: {
                applicationDeletionTimestamp?: components["schemas"]["Timestamp"] | null;
                repoArchived?: boolean;
                gcpTeardownIssue?: {
                    number: number;
                    /** Format: uri */
                    url: string;
                    /** @enum {string} */
                    state?: "open" | "closed";
                } | null;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "decommission";
        };
        SnapshotEvent: {
            /** @constant */
            kind: "snapshot";
            payload: components["schemas"]["AppStatus"];
        };
        StageUpdateEvent: {
            /** @constant */
            kind: "stage-update";
            app: components["schemas"]["AppName"];
            stage: components["schemas"]["Stage"];
            emittedAt: components["schemas"]["Timestamp"];
        };
        OverallUpdateEvent: {
            /** @constant */
            kind: "overall-update";
            app: components["schemas"]["AppName"];
            overall: components["schemas"]["OverallStatus"];
            emittedAt: components["schemas"]["Timestamp"];
        };
        PingEvent: {
            /** @constant */
            kind: "ping";
            emittedAt: components["schemas"]["Timestamp"];
        };
        ErrorEvent: {
            /** @constant */
            kind: "error";
            emittedAt: components["schemas"]["Timestamp"];
            problem: components["schemas"]["Problem"];
        };
        RefreshAccepted: {
            app: components["schemas"]["AppName"];
            /** @constant */
            accepted: true;
            willRecomputeAt: components["schemas"]["Timestamp"];
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checkedAt: components["schemas"]["Timestamp"];
            upstreams: {
                /** @enum {string} */
                name: "argocd" | "kubernetes" | "github" | "sentry";
                /** @enum {string} */
                status: "ok" | "failing" | "unknown";
                lastSuccessAt: components["schemas"]["Timestamp"] | null;
                consecutiveFailures?: number;
            }[];
        };
    };
    responses: {
        /** @description Application not found or not visible to this aggregator. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                /** @description Seconds the caller should wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description ArgoCD Application name. */
        AppName: components["schemas"]["AppName"];
        /**
         * @description Filter to Applications whose source repository matches `owner/repo`.
         *     Used by the `?repo=` fallback in the browser.
         * @example ForumViriumHelsinki/tfds
         */
        RepoFilter: string;
        /**
         * @description Filter to Applications in the given ArgoCD AppProject.
         * @example platform-automation
         */
        ProjectFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApps: {
        parameters: {
            query?: {
                /**
                 * @description Filter to Applications whose source repository matches `owner/repo`.
                 *     Used by the `?repo=` fallback in the browser.
                 * @example ForumViriumHelsinki/tfds
                 */
                repo?: components["parameters"]["RepoFilter"];
                /**
                 * @description Filter to Applications in the given ArgoCD AppProject.
                 * @example platform-automation
                 */
                project?: components["parameters"]["ProjectFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered list of Applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getAppStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ArgoCD Application name. */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    streamAppEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Standard SSE resume header. Server responds with a full snapshot on reconnect regardless of value. */
                "Last-Event-ID"?: string;
            };
            path: {
                /** @description ArgoCD Application name. */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    refreshApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ArgoCD Application name. */
                name: components["parameters"]["AppName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh accepted; results propagate via SSE. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccepted"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Unhealthy — at least one upstream is down. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics in Prometheus text exposition format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
