apiVersion: v1
kind: Service
metadata:
  name: status-aggregator
  namespace: status-aggregator
  labels:
    app.kubernetes.io/name: status-aggregator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: status-aggregator
